const dummyData =
[
    {
        id:1,
        name:"大東洋",
        image:"./img/daitouyou.jpg",
        male:{
            saunaTemp:100,
            coldBath:12,
            airBath:true,
            louryu:true,
            autoLouryu:true,
            selfLouryu:true,
            totonoiSpace:true
        },
        female:{
            saunaTemp:"",
            coldBath:"",
            airBath:false,
            louryu:false,
            autoLouryu:false,
            selfLouryu:false
        },
        price:1300,
        facility:{
            allTime:false,
            restArea:true,
            eatingSpace:true,
            comics:true,
            waterDispenser:true,
            parkingArea:true
        },
        paying:{
            cash:true,
            credit:true,
            eMoney:true
        },
        rental:{
            faceTowel:true,
            bathTowel:false,
            indoorWera:true,
            mat:true
        },
        amenities:{
            shampoo:true,
            conditioner:true,
            bodySoap:true,
            hairDryer:true
        }
    },
    {
        id:2,
        name:"天然温泉　延羽の湯　鶴橋店",
        image:"./img/daitouyou.jpg",
        male:{
            saunaTemp:104,
            coldBath:16.8,
            airBath:true,
            louryu:true,
            autoLouryu:false,
            selfLouryu:true,
            totonoiSpace:true
        },
        female:{
            saunaTemp:98,
            coldBath:16.5,
            airBath:true,
            louryu:true,
            autoLouryu:false,
            selfLouryu:true,
            totonoiSpace:true
        },
        price:900,
        facility:{
            allTime:false,
            restArea:true,
            eatingSpace:true,
            comics:true,
            waterDispenser:true,
            parkingArea:true
        },
        paying:{
            cash:true,
            credit:true,
            eMoney:true
        },
        rental:{
            faceTowel:false,
            bathTowel:true,
            indoorWera:true,
            mat:true
        },
        amenities:{
            shampoo:true,
            conditioner:true,
            bodySoap:true,
            hairDryer:true
        }
    },
    {
        id:3,
        name:"天然温泉　なにわの湯",
        image:"./img/daitouyou.jpg",
        male:{
            saunaTemp:82,
            coldBath:15.8,
            airBath:true,
            louryu:false,
            autoLouryu:true,
            selfLouryu:false,
            totonoiSpace:true
        },
        female:{
            saunaTemp:80,
            coldBath:16,
            airBath:true,
            louryu:false,
            autoLouryu:true,
            selfLouryu:false,
            totonoiSpace:true
        },
        price:850,
        facility:{
            allTime:false,
            restArea:true,
            eatingSpace:true,
            comics:false,
            waterDispenser:true,
            parkingArea:true
        },
        paying:{
            cash:true,
            credit:true,
            eMoney:true
        },
        rental:{
            faceTowel:false,
            bathTowel:false,
            indoorWera:false,
            mat:true
        },
        amenities:{
            shampoo:true,
            conditioner:true,
            bodySoap:true,
            hairDryer:true
        }
    },
];

export default dummyData;
